from . import chat
from . import gerenciamento
from . import conteudo
from . import blog
from . import revisao_ortografica
from . import revisao_tecnica
from . import otimizacao
from . import calendario
from . import briefings
from . import revisao_tecnica2
